version: '3'
services:
  mumble:
    image: superbobdthm/mumble-server
    ports:
      - 64738:64738
      - 64738:64738/udp
    volumes:
      - /mnt/dockerData/mumbleServer:/mumble-server
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 5